spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fundtrans?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 2514632453
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080