app.name=fundRedemption-server

app.group=fund_trans

app.server.port=8030

app.registry.address=nacos://127.0.0.1:8848

rpc.trace.log=true

rpc.trace.type=json

config.location=classpath:middleware.properties
